[package]
name = "cg-core"
description = "Cardigan core services"
autotests = false

version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[features]
test-support = ["dep:mockall"]

[dependencies]
async-trait.workspace = true
chrono.workspace = true
derive_builder.workspace = true
mockall = { workspace = true, optional = true }
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
mockall.workspace = true
insta.workspace = true

[lints]
workspace = true
