use crate::{
    Error,
    addressbook::{Changes, Collection, MultigetResult, Precondition, SyncToken},
    contact::{ETag, Href},
};

/// Driven port for one side's CardDAV address book. One instance is bound to
/// one side; the composition root knows which. `cg-carddav` implements it and
/// `test_support::InMemoryAddressBook` fakes it. Card bodies cross the port as
/// verbatim bytes (PII: never log them).
#[async_trait::async_trait]
#[cfg_attr(any(test, feature = "test-support"), mockall::automock)]
#[allow(unused_lifetimes, reason = "Generated by mockall")]
#[allow(clippy::ref_option_ref, reason = "Generated by mockall's automock on Option<&T> arguments")]
pub trait AddressBook: Send + Sync {
    /// Runs full discovery (principal, address book home set, collection) and
    /// binds the adapter to the resolved collection.
    async fn discover(&self) -> Result<Collection, Error>;

    /// With `None`: the full membership with ETags and a fresh token. With a
    /// token: what changed since it, or `Changes::TokenInvalid` when the
    /// server rejects it. The returned delta is complete: when the server
    /// truncates a `sync-collection` response (RFC 6578: 507 on the request
    /// URI with an intermediate token), the adapter keeps requesting until it
    /// has the whole delta.
    async fn changes_since(&self, token: Option<&SyncToken>) -> Result<Changes, Error>;

    /// Every resource with its ETag (PROPFIND depth 1), for collections that
    /// do not support `sync-collection`.
    async fn list_etags(&self) -> Result<Vec<(Href, ETag)>, Error>;

    /// Fetches any number of cards; the adapter batches requests. Hrefs the
    /// server no longer has come back in `missing`, not as an error.
    async fn multiget(&self, hrefs: &[Href]) -> Result<MultigetResult, Error>;

    /// Writes `body` verbatim, guarded by `precondition`. Returns the new
    /// ETag, or `None` when the server did not send one: the caller must then
    /// fetch it with `multiget` so the next poll recognises its own write. A
    /// failed precondition is `AddressBookError::PreconditionFailed`.
    ///
    /// For a create (`Precondition::IfNoneMatch`), the caller mints `href`: a
    /// new resource name inside the collection (`Collection::addressbook_url`'s
    /// path followed by `<name>.vcf`), expressed like every `Href` as the
    /// server path, not an absolute URL.
    async fn put(&self, href: &Href, body: &[u8], precondition: Precondition) -> Result<Option<ETag>, Error>;

    /// Deletes the resource, guarded by `if_match` when given. A resource
    /// that is already gone is success: a strictly conforming server may
    /// answer `If-Match` on it with 412 rather than 404, so before reporting
    /// `PreconditionFailed` the adapter must confirm the resource still
    /// exists, and report success if it does not.
    async fn delete(&self, href: &Href, if_match: Option<&ETag>) -> Result<(), Error>;
}
