use chrono::{DateTime, Utc};

use crate::{
    Error,
    contact::{CardHash, Href, Side, Uid},
    repository::Transaction,
};

pub type BaselineSkipId = u64;

/// A card initial sync could not pair with certainty (spec: "never guess").
/// It stays unsynced, and must not be treated as a create, until an edit lets
/// it pair cleanly or it is deleted. Keyed by `side` and `href`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BaselineSkip {
    pub id: BaselineSkipId,
    pub version: u64,
    pub side: Side,
    pub href: Href,
    pub uid: Uid,
    /// Canonical hash when skipped, to notice an edit.
    pub content_hash: CardHash,
    /// `CANONICAL_VERSION` that produced `content_hash`.
    pub hash_version: u8,
    /// How many identity-heuristic candidates it had on the other side: 0 or
    /// at least 2 (exactly 1 pairs).
    pub candidate_count: u32,
    pub skipped_at: DateTime<Utc>,
}

/// A skip to store (no id or version yet).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewBaselineSkip {
    pub side: Side,
    pub href: Href,
    pub uid: Uid,
    pub content_hash: CardHash,
    pub hash_version: u8,
    pub candidate_count: u32,
    pub skipped_at: DateTime<Utc>,
}

#[async_trait::async_trait]
#[cfg_attr(test, mockall::automock)]
#[allow(unused_lifetimes, reason = "Generated by mockall")]
pub trait BaselineSkipRepository: Send + Sync {
    /// Replaces every skip with `skips` (a full baseline run). Returns how
    /// many were stored.
    async fn replace_all(&self, transaction: &dyn Transaction, skips: Vec<NewBaselineSkip>) -> Result<u64, Error>;

    /// Inserts the skip for `skip.side`/`skip.href`, or updates it in place
    /// (a re-evaluated card that is still ambiguous).
    async fn upsert(&self, transaction: &dyn Transaction, skip: NewBaselineSkip) -> Result<BaselineSkip, Error>;

    /// Every skip, ordered by id.
    async fn list_all(&self, transaction: &dyn Transaction) -> Result<Vec<BaselineSkip>, Error>;

    /// Removes the skip for a resource (paired cleanly, or deleted). Returns
    /// whether a row was removed.
    async fn delete(&self, transaction: &dyn Transaction, side: Side, href: &Href) -> Result<bool, Error>;

    /// Removes every row (`--reset`); returns how many were removed.
    async fn delete_all(&self, transaction: &dyn Transaction) -> Result<u64, Error>;
}
