use std::{fmt, str::FromStr};

use chrono::{DateTime, Utc};

use crate::{
    Error,
    contact::{Side, Uid},
    repository::Transaction,
};

pub type ConflictId = u64;

/// Where a conflict was detected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConflictOrigin {
    /// Both sides changed the card since the last sync.
    Sync,
    /// Initial sync paired two differing cards (pass 1 or pass 3).
    Baseline,
}

impl ConflictOrigin {
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Sync => "sync",
            Self::Baseline => "baseline",
        }
    }
}

impl FromStr for ConflictOrigin {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "sync" => Ok(Self::Sync),
            "baseline" => Ok(Self::Baseline),
            _ => Err(format!("unknown conflict origin `{s}`")),
        }
    }
}

/// Both versions of a contact at a conflict, kept so the losing edit is
/// recoverable. The vCards are full contact data (PII): `Debug` prints their
/// lengths only, and they must never be logged.
#[derive(Clone, PartialEq, Eq)]
pub struct Conflict {
    pub id: ConflictId,
    /// The contact's UID after resolution. For a baseline pass-3 pair this is
    /// the iCloud card's UID; the Fastmail card keeps its own UID inside its
    /// bytes.
    pub uid: Uid,
    pub origin: ConflictOrigin,
    pub winner: Side,
    /// Verbatim card bytes; parse with `VCard::parse` when needed.
    pub icloud_vcard: Vec<u8>,
    /// Verbatim card bytes; parse with `VCard::parse` when needed.
    pub fastmail_vcard: Vec<u8>,
    pub detected_at: DateTime<Utc>,
}

impl fmt::Debug for Conflict {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Conflict")
            .field("id", &self.id)
            .field("uid", &self.uid)
            .field("origin", &self.origin)
            .field("winner", &self.winner)
            .field("icloud_bytes", &self.icloud_vcard.len())
            .field("fastmail_bytes", &self.fastmail_vcard.len())
            .field("detected_at", &self.detected_at)
            .finish()
    }
}

/// A conflict to record (no id yet). Same PII rules as `Conflict`.
#[derive(Clone, PartialEq, Eq)]
pub struct NewConflict {
    pub uid: Uid,
    pub origin: ConflictOrigin,
    pub winner: Side,
    pub icloud_vcard: Vec<u8>,
    pub fastmail_vcard: Vec<u8>,
    pub detected_at: DateTime<Utc>,
}

impl fmt::Debug for NewConflict {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("NewConflict")
            .field("uid", &self.uid)
            .field("origin", &self.origin)
            .field("winner", &self.winner)
            .field("icloud_bytes", &self.icloud_vcard.len())
            .field("fastmail_bytes", &self.fastmail_vcard.len())
            .field("detected_at", &self.detected_at)
            .finish()
    }
}

#[async_trait::async_trait]
#[cfg_attr(test, mockall::automock)]
#[allow(unused_lifetimes, reason = "Generated by mockall")]
pub trait ConflictRepository: Send + Sync {
    /// Appends a conflict. Rows are never updated or deleted; `--reset`
    /// keeps them.
    async fn add(&self, transaction: &dyn Transaction, new: NewConflict) -> Result<Conflict, Error>;

    /// Every conflict, newest first.
    async fn list_all(&self, transaction: &dyn Transaction) -> Result<Vec<Conflict>, Error>;

    /// Every conflict recorded for `uid`, newest first.
    async fn list_for_uid(&self, transaction: &dyn Transaction, uid: &Uid) -> Result<Vec<Conflict>, Error>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn conflict_origin_round_trips_through_str() {
        for origin in [ConflictOrigin::Sync, ConflictOrigin::Baseline] {
            assert_eq!(origin.as_str().parse::<ConflictOrigin>(), Ok(origin));
        }
        "merge".parse::<ConflictOrigin>().unwrap_err();
    }

    #[test]
    fn conflict_debug_omits_card_content() {
        let conflict = Conflict {
            id: 1,
            uid: Uid::from("u1"),
            origin: ConflictOrigin::Sync,
            winner: Side::ICloud,
            icloud_vcard: b"BEGIN:VCARD\r\nEMAIL:jane@example.com\r\nEND:VCARD\r\n".to_vec(),
            fastmail_vcard: b"BEGIN:VCARD\r\nTEL:+1 555 0100\r\nEND:VCARD\r\n".to_vec(),
            detected_at: DateTime::<Utc>::UNIX_EPOCH,
        };
        let debug = format!("{conflict:?}");
        assert!(debug.contains("u1"), "{debug}");
        assert!(!debug.contains("jane@example.com") && !debug.contains("555"), "card content leaked: {debug}");

        let new = NewConflict {
            uid: conflict.uid.clone(),
            origin: conflict.origin,
            winner: conflict.winner,
            icloud_vcard: conflict.icloud_vcard.clone(),
            fastmail_vcard: conflict.fastmail_vcard.clone(),
            detected_at: conflict.detected_at,
        };
        let debug = format!("{new:?}");
        assert!(!debug.contains("jane@example.com") && !debug.contains("555"), "card content leaked: {debug}");
    }
}
