use chrono::{DateTime, Utc};

use crate::{
    Error,
    contact::{CardHash, ETag, Href, Side, Uid, VCard},
    repository::Transaction,
};

pub type ContactStateId = u64;

/// One side's resource for a synced contact.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SideState {
    pub href: Href,
    pub etag: ETag,
    /// When this side last reported the card (poll bookkeeping).
    pub last_seen_at: DateTime<Utc>,
}

/// What the daemon last synced for one contact. A row exists only once the
/// card is on both sides; it is keyed by `uid`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContactState {
    pub id: ContactStateId,
    /// Optimistic-lock version: `update` fails with `Conflict` when the stored
    /// row has moved on.
    pub version: u64,
    pub uid: Uid,
    pub icloud: SideState,
    pub fastmail: SideState,
    /// Canonical hash as of the last successful sync.
    pub content_hash: CardHash,
    /// `CANONICAL_VERSION` that produced `content_hash`. A mismatch means the
    /// hash is stale, not that the card changed: re-baseline, don't sync.
    pub hash_version: u8,
    /// The card's oversize photo was stripped on sync; compare with
    /// `HashOptions { exclude_photo: true, .. }`.
    pub photo_stripped: bool,
    /// The card both sides held after the last successful sync, verbatim.
    /// Full contact data (PII): never log it.
    pub last_synced_vcard: VCard,
    pub last_synced_at: DateTime<Utc>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl ContactState {
    pub fn side(&self, side: Side) -> &SideState {
        match side {
            Side::ICloud => &self.icloud,
            Side::Fastmail => &self.fastmail,
        }
    }
}

/// A contact state row to insert (no id, version or row timestamps yet).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewContactState {
    pub uid: Uid,
    pub icloud: SideState,
    pub fastmail: SideState,
    pub content_hash: CardHash,
    pub hash_version: u8,
    pub photo_stripped: bool,
    pub last_synced_vcard: VCard,
    pub last_synced_at: DateTime<Utc>,
}

#[async_trait::async_trait]
#[cfg_attr(test, mockall::automock)]
#[allow(unused_lifetimes, reason = "Generated by mockall")]
pub trait ContactStateRepository: Send + Sync {
    /// Every contact state row, ordered by id (the planner's snapshot).
    async fn list_all(&self, transaction: &dyn Transaction) -> Result<Vec<ContactState>, Error>;

    async fn find_by_uid(&self, transaction: &dyn Transaction, uid: &Uid) -> Result<Option<ContactState>, Error>;

    /// Inserts a row. A duplicate `uid` or per-side `href` is `Constraint`.
    async fn add(&self, transaction: &dyn Transaction, new: NewContactState) -> Result<ContactState, Error>;

    /// Writes every field of `state` to the row with `state.id`, provided the
    /// stored version still equals `state.version`; returns the row with its
    /// bumped version. `last_seen_at` never moves backwards: for each side it
    /// keeps the later of the stored value and `state.<side>.last_seen_at`,
    /// since `mark_seen` updates it without bumping `version`. A missing row
    /// is `NotFound`; a moved-on row is `Conflict`.
    async fn update(&self, transaction: &dyn Transaction, state: ContactState) -> Result<ContactState, Error>;

    /// Sets `side`'s `last_seen_at` for every listed uid that has a row,
    /// without bumping versions. Returns how many rows changed.
    async fn mark_seen(&self, transaction: &dyn Transaction, side: Side, uids: &[Uid], seen_at: DateTime<Utc>) -> Result<u64, Error>;

    /// Removes the row for `uid`; `NotFound` when there is none.
    async fn delete_by_uid(&self, transaction: &dyn Transaction, uid: &Uid) -> Result<(), Error>;

    /// Removes every row (`--reset`); returns how many were removed.
    async fn delete_all(&self, transaction: &dyn Transaction) -> Result<u64, Error>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::contact::HashOptions;

    #[test]
    fn side_selects_the_matching_side_state() {
        let vcard = VCard::parse("BEGIN:VCARD\r\nVERSION:3.0\r\nUID:u1\r\nEND:VCARD\r\n").expect("card parses");
        let seen = DateTime::<Utc>::UNIX_EPOCH;
        let side = |href: &str| SideState {
            href: Href::from(href),
            etag: ETag::from("\"e\""),
            last_seen_at: seen,
        };
        let state = ContactState {
            id: 1,
            version: 1,
            uid: Uid::from("u1"),
            icloud: side("/icloud/u1.vcf"),
            fastmail: side("/fastmail/u1.vcf"),
            content_hash: vcard.canonical_hash(HashOptions::default()),
            hash_version: 1,
            photo_stripped: false,
            last_synced_vcard: vcard,
            last_synced_at: seen,
            created_at: seen,
            updated_at: seen,
        };
        assert_eq!(state.side(Side::ICloud).href.as_str(), "/icloud/u1.vcf");
        assert_eq!(state.side(Side::Fastmail).href.as_str(), "/fastmail/u1.vcf");
    }
}
