use chrono::{DateTime, Utc};

use crate::{Error, contact::Side, repository::Transaction};

/// Per-side discovery results and incremental-sync position.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Endpoint {
    pub side: Side,
    /// The address book collection being synced.
    pub addressbook_url: String,
    /// The host principal discovery resolved (iCloud's numbered `pXX-` host).
    pub discovered_host: String,
    /// RFC 6578 sync token; `None` forces a full ETag comparison.
    pub sync_token: Option<String>,
    pub updated_at: DateTime<Utc>,
}

#[async_trait::async_trait]
#[cfg_attr(test, mockall::automock)]
#[allow(unused_lifetimes, reason = "Generated by mockall")]
pub trait EndpointRepository: Send + Sync {
    async fn find(&self, transaction: &dyn Transaction, side: Side) -> Result<Option<Endpoint>, Error>;

    /// Records discovery results for `side`, inserting the row on first
    /// discovery. When `addressbook_url` differs from the stored one, the sync
    /// token is cleared: a token for another collection must never be
    /// replayed.
    async fn upsert_discovery(&self, transaction: &dyn Transaction, side: Side, addressbook_url: &str, discovered_host: &str) -> Result<Endpoint, Error>;

    /// Stores (or with `None`, clears) the sync token. `NotFound` before
    /// discovery.
    async fn set_sync_token(&self, transaction: &dyn Transaction, side: Side, sync_token: Option<String>) -> Result<(), Error>;

    /// Removes every row (`--reset`); returns how many were removed.
    async fn delete_all(&self, transaction: &dyn Transaction) -> Result<u64, Error>;
}
