use std::fmt;

use chrono::{DateTime, Utc};

use crate::{
    Error,
    contact::{Href, Uid},
    repository::Transaction,
};

pub type PendingRecreateId = u64;

/// A Recreate that has deleted, or is about to delete, the old Fastmail card
/// (CG-8 Decision 11). `card` is the `create_fastmail` bytes: full contact
/// data (PII), so `Debug` prints its length only and it must never be logged.
#[derive(Clone, PartialEq, Eq)]
pub struct PendingRecreate {
    pub id: PendingRecreateId,
    /// The contact's UID after the Recreate (the iCloud card's UID).
    pub uid: Uid,
    pub old_fastmail_href: Href,
    /// The UID the old Fastmail card carried.
    pub old_fastmail_uid: Uid,
    /// Where the Recreate PUTs the card; replay uses it to tell whether the
    /// create already happened.
    pub new_fastmail_href: Href,
    /// Verbatim card bytes.
    pub card: Vec<u8>,
    pub created_at: DateTime<Utc>,
}

impl fmt::Debug for PendingRecreate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("PendingRecreate")
            .field("id", &self.id)
            .field("uid", &self.uid)
            .field("old_fastmail_href", &self.old_fastmail_href)
            .field("old_fastmail_uid", &self.old_fastmail_uid)
            .field("new_fastmail_href", &self.new_fastmail_href)
            .field("card_bytes", &self.card.len())
            .field("created_at", &self.created_at)
            .finish()
    }
}

/// A Recreate to journal (no id yet). Same PII rules as `PendingRecreate`.
#[derive(Clone, PartialEq, Eq)]
pub struct NewPendingRecreate {
    pub uid: Uid,
    pub old_fastmail_href: Href,
    pub old_fastmail_uid: Uid,
    pub new_fastmail_href: Href,
    pub card: Vec<u8>,
    pub created_at: DateTime<Utc>,
}

impl fmt::Debug for NewPendingRecreate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("NewPendingRecreate")
            .field("uid", &self.uid)
            .field("old_fastmail_href", &self.old_fastmail_href)
            .field("old_fastmail_uid", &self.old_fastmail_uid)
            .field("new_fastmail_href", &self.new_fastmail_href)
            .field("card_bytes", &self.card.len())
            .field("created_at", &self.created_at)
            .finish()
    }
}

#[async_trait::async_trait]
#[cfg_attr(test, mockall::automock)]
#[allow(unused_lifetimes, reason = "Generated by mockall")]
pub trait PendingRecreateRepository: Send + Sync {
    /// Records the Recreate for `new.uid`, replacing any earlier row for it.
    async fn upsert(&self, transaction: &dyn Transaction, new: NewPendingRecreate) -> Result<PendingRecreate, Error>;

    /// Every row, oldest (lowest id) first.
    async fn list_all(&self, transaction: &dyn Transaction) -> Result<Vec<PendingRecreate>, Error>;

    /// Removes the row for `uid`; returns whether one was removed. `--reset`
    /// keeps these rows, so there is no `delete_all`.
    async fn delete(&self, transaction: &dyn Transaction, uid: &Uid) -> Result<bool, Error>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn debug_omits_card_content() {
        let card = b"BEGIN:VCARD\r\nEMAIL:jane@example.com\r\nEND:VCARD\r\n".to_vec();
        let pending = PendingRecreate {
            id: 7,
            uid: Uid::from("ic-1"),
            old_fastmail_href: Href::from("/dav/old.vcf"),
            old_fastmail_uid: Uid::from("fm-1"),
            new_fastmail_href: Href::from("/dav/new.vcf"),
            card: card.clone(),
            created_at: DateTime::<Utc>::UNIX_EPOCH,
        };
        let debug = format!("{pending:?}");
        assert!(debug.contains("ic-1") && debug.contains("/dav/new.vcf"), "{debug}");
        assert!(!debug.contains("jane@example.com"), "card content leaked: {debug}");

        let new = NewPendingRecreate {
            uid: pending.uid.clone(),
            old_fastmail_href: pending.old_fastmail_href.clone(),
            old_fastmail_uid: pending.old_fastmail_uid.clone(),
            new_fastmail_href: pending.new_fastmail_href.clone(),
            card,
            created_at: pending.created_at,
        };
        let debug = format!("{new:?}");
        assert!(!debug.contains("jane@example.com"), "card content leaked: {debug}");
    }
}
