[package]
name = "cg-carddav"
description = "Cardigan CardDAV adapter"
autotests = false

version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
cg-core.workspace = true

async-trait.workspace = true
httpdate.workspace = true
percent-encoding.workspace = true
reqwest.workspace = true
roxmltree.workspace = true
secrecy.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
tokio.workspace = true
tracing-subscriber.workspace = true
wiremock.workspace = true

[lints]
workspace = true
